## Part 1: Preprocessing

In [27]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [28]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [29]:
# Create y_df with the Attrition and Department columns

y_df = attrition_df[["Attrition", "Department"]]
y_df

Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [31]:
# Create a list of at least 10 column names to use as X data
columns = ['Age', 'BusinessTravel', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate', 'OverTime',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']


# Create X_df using your selected columns
X_df = attrition_df[columns]


# Show the data types for X_df
X_df.dtypes



Age                         int64
BusinessTravel             object
DistanceFromHome            int64
Education                   int64
EducationField             object
EnvironmentSatisfaction     int64
HourlyRate                  int64
OverTime                   object
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [32]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size = 0.2, random_state = 42)


In [33]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

def create_dummies(dataframe, column):
    # Transform the column using get_dummies()
    dummy_columns = pd.get_dummies(dataframe[column], dtype = "int")
    # Concatenate the dummy_columns onto the original dataframe, and delete the original column that was dummied
    dataframe = pd.concat([dataframe, dummy_columns], axis = 1).drop(columns = column)
    return dataframe


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
le = LabelEncoder()

columns_dummy = ["BusinessTravel", "EducationField"]
columns_le = ["OverTime"]

X_train = create_dummies(X_train, columns_dummy)
X_test = create_dummies(X_test, columns_dummy)

X_train['OverTime'] = le.fit_transform(X_train['OverTime'])

X_test['OverTime'] = le.fit_transform(X_test['OverTime'])








In [42]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled)

[[-1.38855944  1.44039645 -0.86335572 ... -0.67620195 -0.24966102
   3.2624476 ]
 [-2.04073779 -0.52269928 -0.86335572 ... -0.67620195 -0.24966102
  -0.30651833]
 [-0.84507748  1.31770296 -0.86335572 ... -0.67620195 -0.24966102
  -0.30651833]
 ...
 [-1.60595222 -0.76808624  1.06322176 ... -0.67620195 -0.24966102
  -0.30651833]
 [-0.84507748  0.45884859 -0.86335572 ... -0.67620195  4.0054311
  -0.30651833]
 [ 1.43754676 -0.03192534  0.09993302 ... -0.67620195 -0.24966102
  -0.30651833]]


In [43]:
# Create a OneHotEncoder for the Department column
dept_encoder = OneHotEncoder(sparse_output = False)

# Fit the encoder to the training data
y_train_dept = y_train["Department"].values.reshape(-1, 1)
dept_encoded = dept_encoder.fit(y_train_dept)

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dept_encoded = dept_encoder.transform(y_train_dept)
y_test_dept_encoded = dept_encoder.transform(y_test["Department"].values.reshape(-1, 1))
print(y_train_dept_encoded)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
# Create a OneHotEncoder for the Attrition column
attr_encoder = OneHotEncoder(sparse_output = False)

# Fit the encoder to the training data
y_train_attr = y_train["Attrition"].values.reshape(-1, 1)
attr_encoded = attr_encoder.fit(y_train_attr)

# Create two new variables by applying the encoder
# to the training and testing data
y_train_attr_encoded = attr_encoder.transform(y_train_attr)
y_test_attr_encoded = attr_encoder.transform(y_test["Attrition"].values.reshape(-1, 1))
print(y_train_attr_encoded)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [45]:
# Find the number of columns in the X training data
X_train.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(X_train.shape[1],), name='input_features')

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu', name = 'shared_layer1')(input_layer)
shared_layer2 = layers.Dense(128, activation='relu', name = 'shared_layer2')(shared_layer1)

In [46]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_layer1 = layers.Dense(32, activation='relu', name = 'dept_layer_hidden')(shared_layer2)

# Create the output layer
dept_output_layer = layers.Dense(3, activation = "softmax", name="dept_output")(dept_layer1)

In [47]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attr_layer1 = layers.Dense(32, activation='relu', name = 'attr_layer_hidden')(shared_layer2)

# Create the output layer
attr_output_layer = layers.Dense(2, activation = "sigmoid", name="attr_output")(attr_layer1)

In [48]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output_layer, attr_output_layer])

# Compile the model
model.compile(optimizer='adam',
              loss={'dept_output': 'categorical_crossentropy', 'attr_output': 'binary_crossentropy'},
              metrics={'dept_output': 'accuracy', 'attr_output': 'accuracy'})

# Summarize the model
model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_features (InputLayer  [(None, 20)]                 0         []                            
 )                                                                                                
                                                                                                  
 shared_layer1 (Dense)       (None, 64)                   1344      ['input_features[0][0]']      
                                                                                                  
 shared_layer2 (Dense)       (None, 128)                  8320      ['shared_layer1[0][0]']       
                                                                                                  
 dept_layer_hidden (Dense)   (None, 32)                   4128      ['shared_layer2[0][0]'] 

In [49]:
# Train the model
model.fit(
    X_train_scaled,
    {
        'dept_output': y_train_dept_encoded,
        'attr_output': y_train_attr_encoded,
    },
    epochs=50,
    batch_size=32,
    validation_split=0.2
)


Epoch 1/50
30/30 [==============================] - 3s 32ms/step - loss: 1.4018 - dept_output_loss: 0.9077 - attr_output_loss: 0.4942 - dept_output_accuracy: 0.5532 - attr_output_accuracy: 0.8096 - val_loss: 1.2615 - val_dept_output_loss: 0.7718 - val_attr_output_loss: 0.4896 - val_dept_output_accuracy: 0.6314 - val_attr_output_accuracy: 0.7966
Epoch 2/50
30/30 [==============================] - 0s 6ms/step - loss: 1.0826 - dept_output_loss: 0.6704 - attr_output_loss: 0.4122 - dept_output_accuracy: 0.7309 - attr_output_accuracy: 0.8404 - val_loss: 1.1053 - val_dept_output_loss: 0.6704 - val_attr_output_loss: 0.4348 - val_dept_output_accuracy: 0.7797 - val_attr_output_accuracy: 0.7966
Epoch 3/50
30/30 [==============================] - 0s 7ms/step - loss: 0.9793 - dept_output_loss: 0.5933 - attr_output_loss: 0.3860 - dept_output_accuracy: 0.7745 - attr_output_accuracy: 0.8426 - val_loss: 1.0620 - val_dept_output_loss: 0.6364 - val_attr_output_loss: 0.4256 - val_dept_output_accuracy: 0.7

In [50]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test_scaled, {'dept_output': y_test_dept_encoded, 'attr_output': y_test_attr_encoded})
test_results

10/10 [==============================] - 0s 3ms/step - loss: 2.1705 - dept_output_loss: 1.4994 - attr_output_loss: 0.6711 - dept_output_accuracy: 0.6735 - attr_output_accuracy: 0.8367


[2.170461893081665,
 1.4993641376495361,
 0.6710978746414185,
 0.6734693646430969,
 0.8367347121238708]

In [51]:
# Print the accuracy for both department and attrition
print(f"Department predictions accuracy: {test_results[3]}")
print(f"Attrition predictions accuracy: {test_results[4]}")

Department predictions accuracy: 0.6734693646430969
Attrition predictions accuracy: 0.8367347121238708


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Imbalanced Dataset: Use balanced accuracy instead of regular accuracy.
2. Activation Functions:
    Softmax for multi-class (3-option Department).
    Sigmoid for binary (Attrition).
3. Feature Selection: Remove highly correlated variables.
